runtime: custom
env: flex

# 環境変数の設定
env_variables:
  BOT_TOKEN: ${BOT_TOKEN}
  TARGET_CHANNEL_ID: ${TARGET_CHANNEL_ID}
  LOG_CHANNEL_ID: ${LOG_CHANNEL_ID}

# Dockerイメージの指定
image: IMAGE_URL

# その他の設定
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
