name: Build and Deploy to GCP Artifact Registry

on:
  workflow_dispatch:    # 手動実行のためのトリガー


env:
  PROJECT_ID: local-llm-discord-server  # あなたのGCPプロジェクトIDに置き換えてください
  REGION: us-central1  # Artifact Registryのリージョンに合わせて変更してください
  REPOSITORY: askmeanything  # Artifact Registryのリポジトリ名に置き換えてください
  IMAGE: discord-bot  # あなたのDockerイメージ名に置き換えてください

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_API_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }} .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}

    - name: Clean up
      if: always()
      run: |
        docker rmi ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}