name: Deploy to Google App Engine Flexible

on:
  workflow_dispatch:  # 手動実行のためのトリガー

env:
  PROJECT_ID: local-llm-discord-server  # あなたのGCPプロジェクトIDに置き換えてください
  REGION: asia-northeast1  # Artifact Registryのリージョンに合わせて変更してください
  REPOSITORY: askmeanything  # Artifact Registryのリポジトリ名に置き換えてください
  IMAGE: discord-bot  # あなたのDockerイメージ名に置き換えてください

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }} .
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}

    - name: Update app.yaml
      run: |
        sed -i 's|IMAGE_URL|${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}|g' app.yaml

    - name: Deploy to App Engine
      run: |
        gcloud app deploy app.yaml --project=${{ env.PROJECT_ID }} --quiet

    - name: Display app URL
      run: |
        gcloud app browse --project=${{ env.PROJECT_ID }}

    - name: Clean up
      if: always()
      run: |
        docker rmi ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}